use_frameworks!

platform :ios, '14.0'

source 'https://cdn.cocoapods.org/' # Default global repository
source 'https://github.com/hotmic-wp/hotmic-media-player-cocoapod-specs.git'
source 'https://github.com/bitmovin/cocoapod-specs.git'

target 'HotMicMediaPlayer_Example' do
  pod 'HotMicMediaPlayer', :path => '../'

  target 'HotMicMediaPlayer_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
