use_frameworks!

platform :ios, '9.0'

target 'HotMicMediaPlayer_Example' do
  pod 'HotMicMediaPlayer', :path => '../'

  target 'HotMicMediaPlayer_Tests' do
    inherit! :search_paths

    
  end
end
